async (page) => {
 const assert=(condition,message)=>{if(!condition)throw new Error(message);};
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto('http://127.0.0.1:5173/');
 await page.getByRole('heading',{name:'I Robot',exact:true}).waitFor();
 await page.getByRole('button',{name:'ENG',exact:true}).click();
 assert(await page.locator('html').getAttribute('lang')==='en','English language');
 await page.reload();await page.getByRole('heading',{name:'I Robot',exact:true}).waitFor();
 assert(await page.locator('html').getAttribute('lang')==='en','Language persists');
 if(await page.getByRole('button',{name:'Motion: On',exact:true}).count())await page.getByRole('button',{name:'Motion: On',exact:true}).click();
 await page.setViewportSize({width:1440,height:1000});
 await page.screenshot({path:'output/playwright/desktop-english.png',fullPage:true});
 await page.locator('.arrows').getByRole('button',{name:'Next record',exact:true}).click();
 assert(await page.locator('.record-title h2').textContent()==='Yeni Bir Gün','Next record');
 await page.keyboard.press('ArrowLeft');
 assert(await page.locator('.record-title h2').textContent()==='I Robot','Keyboard previous');
 await page.locator('.record-stage').hover();await page.mouse.wheel(0,140);
 await page.getByRole('heading',{name:'Yeni Bir Gün',exact:true}).waitFor();
 await page.getByRole('button',{name:'Search & filter',exact:true}).click();
 await page.getByRole('searchbox').fill('Pink Floyd');
 assert((await page.locator('.record-number').textContent()).includes('/ 03'),'Search results');
 await page.getByRole('searchbox').fill('zzzz-no-record');
 await page.getByRole('heading',{name:'No records in this crate.'}).waitFor();
 await page.locator('.empty').getByRole('button',{name:'Clear filters'}).click();
 await page.getByLabel('All formats',{exact:true}).selectOption('single');
 assert((await page.locator('.record-number').textContent()).includes('/ 04'),'Four singles');
 await page.getByRole('button',{name:'Put it on the turntable',exact:true}).click();
 assert(await page.locator('.tracklist li').count()===2,'Single tracklist');
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Clear filters',exact:true}).click();
 await page.getByLabel('All genres',{exact:true}).selectOption('Prog Rock');
 assert((await page.locator('.record-tags').textContent()).includes('Prog Rock'),'Genre filter');
 await page.getByRole('button',{name:'Clear filters',exact:true}).click();
 await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('button',{name:'All records',exact:true}).click();
 assert(await page.locator('.grid-record').count()===58,'Grid has 58 releases');
 const ids=await page.locator('.grid-record').evaluateAll(items=>items.map(item=>item.dataset.record));
 for(const id of ids){
  await page.locator(`.grid-record[data-record="${id}"]`).click();
  assert(await page.locator('#detail-title').textContent(),'Release title '+id);
  assert(await page.locator('.tracklist li').count()>0,'Tracks '+id);
  assert(await page.locator('.summary').textContent(),'English notes '+id);
  assert(await page.locator('.unpacking-sleeve img').evaluate(img=>img.complete&&img.naturalWidth>0),'Local artwork '+id);
  await page.keyboard.press('Escape');
 }
 await page.getByRole('button',{name:'Back to the collection',exact:true}).click();
 await page.getByRole('button',{name:'УКР',exact:true}).click();
 await page.getByRole('button',{name:'Покласти на програвач',exact:true}).click();
 assert(await page.locator('.story-note').count()===4,'Ukrainian extended notes');
 await page.locator('.story-note summary').first().click();
 assert(await page.locator('.story-note').first().getAttribute('open')!==null,'Expandable history');
 await page.screenshot({path:'output/playwright/detail-desktop.png'});
 await page.keyboard.press('Escape');
 for(const width of [320,390,768,1024,1440]){
  await page.setViewportSize({width,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No page overflow at '+width);
 }
 await page.setViewportSize({width:390,height:844});
 await page.evaluate(()=>scrollTo(0,0));
 await page.screenshot({path:'output/playwright/mobile-ukrainian.png',fullPage:true});
 await page.getByRole('button',{name:'Покласти на програвач',exact:true}).click();
 assert(await page.locator('#detail-dialog').evaluate(el=>el.scrollWidth<=el.clientWidth),'No mobile detail overflow');
 await page.screenshot({path:'output/playwright/detail-mobile.png'});
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Трохи про неї',exact:true}).last().click();
 assert(await page.locator('#about-dialog').isVisible(),'About available on mobile');
 await page.keyboard.press('Escape');
 await page.goto('http://127.0.0.1:5173/#record-773190');
 await page.locator('#detail-title').waitFor();
 assert(await page.locator('#detail-title').textContent()==='I Robot','Direct record URL');
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Покласти на програвач',exact:true}).click();
 await page.goBack();
 assert(!await page.locator('#detail-dialog').isVisible(),'Browser back closes release');
 await page.goForward();
 assert(await page.locator('#detail-dialog').isVisible(),'Browser forward opens release');
 assert(errors.length===0,'No runtime errors: '+errors.join('; '));
 console.log('PASS: bilingual UI, persistence, keyboard/wheel, search, empty state, genres, singles, all 58 details and covers, 5 viewport widths, dialogs, deep links, browser history; no runtime errors.');
}
