import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {filterRecords,nextIndex,escapeHtml,safeUrl,markdown} from '../src/catalogue.js';
import {summaries} from '../src/english.js';
const records=JSON.parse(readFileSync(new URL('../public/collection.json',import.meta.url)));
test('all 58 distinct pressings have local covers, bilingual notes, metadata and tracks',()=>{
 assert.equal(records.length,58);assert.equal(new Set(records.map(r=>r.id)).size,58);assert.equal(summaries.length,58);
 for(const r of records){assert.ok(existsSync(new URL('../public'+r.cover,import.meta.url)),r.title);assert.ok(r.summaryUk.length>30);assert.ok(summaries[r.number-1].length>30);assert.ok(r.tracks.length>0,r.title);for(const track of r.tracks)assert.ok(track.title.length>0,`${r.title}: ${track.position}`);assert.ok(r.label);assert.ok(r.format);}
});
test('case-insensitive English and Ukrainian search and whitespace',()=>{assert.equal(filterRecords(records,{query:'  pInK FlOyD  '}).length,3);assert.equal(filterRecords(records,{query:'ПАЛІНДРОМ'}).length,1);assert.equal(filterRecords(records,{query:'nonexistent12345'}).length,0);});
test('format, genre and search combine, and do not mutate the catalogue',()=>{assert.equal(filterRecords(records,{format:'single'}).length,4);const rs=filterRecords(records,{query:'Yes',genre:'Prog Rock'});assert.ok(rs.length>0);assert.ok(rs.every(r=>r.genres.includes('Prog Rock')));const initial=records.map(r=>r.id);filterRecords(records,{sort:'artist'});assert.deepEqual(records.map(r=>r.id),initial);});
test('year ordering is descending and deterministic',()=>{const sorted=filterRecords(records,{sort:'year'});const years=sorted.map(r=>Number(r.original.match(/\d{4}/)?.[0])||0);assert.deepEqual(years,[...years].sort((a,b)=>b-a));});
test('carousel wraps in either direction and handles empty results',()=>{assert.equal(nextIndex(57,1,58),0);assert.equal(nextIndex(0,-1,58),57);assert.equal(nextIndex(0,1,0),0);assert.equal(nextIndex(0,58,58),0);});
test('source Markdown cannot inject active HTML or unsafe URLs',()=>{assert.equal(escapeHtml('<script>"&'), '&lt;script&gt;&quot;&amp;');assert.equal(safeUrl('javascript:alert(1)'),'#');assert.equal(safeUrl('https://discogs.com/'),'https://discogs.com/');assert.ok(!markdown('<img src=x onerror=alert(1)>').includes('<img'));assert.ok(markdown('[Discogs](https://discogs.com/)').includes('rel="noopener noreferrer"'));});
test('known multiline and timed tracklists survive import',()=>{const robot=records.find(r=>r.number===19);assert.equal(robot.tracks[0].title,'I Robot');assert.equal(robot.tracks[0].duration,'6:06');const soundtrack=records.find(r=>r.number===24);assert.equal(soundtrack.tracks.length,12);assert.ok(soundtrack.tracks[0].title.includes('The Woman In You'));});
test('PWA manifest has installable local icons',()=>{const manifest=JSON.parse(readFileSync(new URL('../public/manifest.webmanifest',import.meta.url)));assert.equal(manifest.display,'standalone');for(const i of manifest.icons)assert.ok(existsSync(new URL(i.src,new URL('../public/',import.meta.url))));});
test('artist and album headings match the supplied catalogue exactly',()=>{const source=readFileSync(new URL('../vinyl_collection.md',import.meta.url),'utf8');const headings=[...source.matchAll(/^### (\d+)\. (.*?) — (.*?)$/gm)];assert.equal(headings.length,58);for(const [,n,artist,title]of headings){const r=records[Number(n)-1];assert.equal(r.title,title);assert.equal(r.artist,artist.replace(/\*+$/,''));}});
test('each release has a local multi-photo gallery with source provenance',()=>{const galleries=JSON.parse(readFileSync(new URL('../public/gallery.json',import.meta.url)));assert.equal(Object.keys(galleries).length,58);for(const r of records){const photos=galleries[r.id];assert.ok(photos.length>=2,r.title);for(const photo of photos){assert.ok(existsSync(new URL('../public'+photo.src,import.meta.url)),photo.src);assert.ok(photo.source.startsWith('https://i.discogs.com/'));assert.equal(photo.releaseUrl,r.url);}}});
test('artist archives have local files, dates, distinct provenance and licenses',()=>{const archive=JSON.parse(readFileSync(new URL('../public/archive.json',import.meta.url)));assert.ok(Object.keys(archive).length>=40);for(const [id,photos]of Object.entries(archive)){assert.ok(records.some(r=>String(r.id)===id));for(const photo of photos){assert.ok(existsSync(new URL('../public'+photo.src,import.meta.url)));assert.equal(photo.kind,'archive');assert.ok(photo.caption);assert.ok(photo.license);assert.ok(photo.source.startsWith('https://commons.wikimedia.org/'));}}assert.equal(archive['12112689'][0].date,'1998');});
