async page => {
 const assert=(v,m)=>{if(!v)throw Error(m);};
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='warning')errors.push(m.text());});
 await page.goto('http://127.0.0.1:5173/');
 await page.evaluate(()=>{localStorage.setItem('vinyl-language','en');localStorage.setItem('vinyl-motion','on');});
 await page.emulateMedia({reducedMotion:'no-preference'});await page.reload();
 await page.setViewportSize({width:1440,height:1000});
 await page.getByRole('heading',{name:'I Robot',exact:true}).waitFor();
 await page.waitForFunction(()=>document.documentElement.dataset.lighting==='/covers/19.jpg');
 const firstLight=await page.locator('html').evaluate(el=>el.style.getPropertyValue('--album-light'));
 await page.locator('.main-record').evaluate(el=>Promise.all(el.getAnimations().map(a=>a.finished)));
 const rect=await page.locator('.front-sleeve').boundingBox();
 await page.mouse.move(rect.x+rect.width*.7,rect.y+rect.height*.55);await page.mouse.down();
 await page.mouse.move(rect.x+rect.width*.7-100,rect.y+rect.height*.55,{steps:10});
 assert(await page.locator('.record-stage').evaluate(el=>el.classList.contains('dragging')),'Live crate drag');
 assert(await page.locator('.main-record').evaluate(el=>el.style.translate!=='') ,'Sleeve follows drag');
 await page.mouse.up();
 await page.getByRole('heading',{name:'Yeni Bir Gün',exact:true}).waitFor();
 assert(!await page.locator('#detail-dialog').isVisible(),'Drag does not open record');
 await page.waitForFunction(()=>document.documentElement.dataset.lighting==='/covers/20.jpg');
 assert(await page.locator('html').evaluate(el=>el.style.getPropertyValue('--album-light'))!==firstLight,'Album-specific light');
 await page.keyboard.press('ArrowLeft');await page.getByRole('heading',{name:'I Robot',exact:true}).waitFor();
 await page.getByRole('button',{name:'Put it on the turntable',exact:true}).click();
 assert(await page.locator('.transfer-layer').isVisible(),'Continuous transfer exists');
 await page.screenshot({path:'output/playwright/sleeve-transfer.png'});
 await page.locator('.transfer-layer').waitFor({state:'detached'});
 assert(await page.locator('.side-indicator').innerText()==='Side A','Initial side');
 await page.getByRole('button',{name:'Flip record',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.side-indicator').textContent==='Side B');
 assert(await page.locator('.tracklist li:visible').count()===5,'Side B tracks');
 await page.getByRole('button',{name:'All tracks',exact:true}).click();
 assert(await page.locator('.tracklist li:visible').count()===10,'All tracks restored');
 const arm=page.getByRole('slider',{name:'Tonearm position'});await arm.focus();await page.keyboard.press('Home');
 assert(await page.locator('.turntable').evaluate(el=>el.classList.contains('paused')),'Park tonearm pauses');
 await page.keyboard.press('End');assert(!await page.locator('.turntable').evaluate(el=>el.classList.contains('paused')),'Lower tonearm resumes');
 const armBox=await arm.boundingBox();await page.mouse.move(armBox.x+armBox.width/2,armBox.y+armBox.height/2);await page.mouse.down();await page.mouse.move(armBox.x+armBox.width/2+80,armBox.y+armBox.height/2,{steps:8});await page.mouse.up();assert(Number(await arm.getAttribute('aria-valuenow'))<8,'Physical tonearm drag parks arm');await arm.focus();await page.keyboard.press('End');
 const disc=page.getByRole('button',{name:'Hold to slow the record'});await disc.focus();await page.keyboard.down('Space');
 await page.waitForFunction(()=>document.querySelector('.playing-disc').getAnimations().some(a=>a.animationName==='spin'&&a.playbackRate<.2));
 await page.keyboard.up('Space');await page.waitForFunction(()=>document.querySelector('.playing-disc').getAnimations().some(a=>a.animationName==='spin'&&a.playbackRate>.95));
 await page.screenshot({path:'output/playwright/interactive-turntable.png'});
 await page.keyboard.press('Escape');
 await page.locator('.transfer-layer').waitFor({state:'visible'});await page.locator('#detail-dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Record room',exact:true}).click();
 assert(await page.locator('body').evaluate(el=>el.classList.contains('record-room')),'Room entered');
 assert(await page.getByRole('button',{name:'Exit record room ×',exact:true}).isVisible(),'Persistent room exit');
 await page.evaluate(()=>document.activeElement.blur());await page.mouse.move(40,350);await page.waitForFunction(()=>document.body.classList.contains('room-idle'));assert(await page.locator('.room-exit').isVisible(),'Idle mode keeps exit visible');await page.mouse.move(70,370);assert(!await page.locator('body').evaluate(el=>el.classList.contains('room-idle')),'Movement reveals controls');await page.screenshot({path:'output/playwright/record-room.png'});
 await page.locator('.room-exit').click();assert(!await page.locator('body').evaluate(el=>el.classList.contains('record-room')),'Room exits');
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Put it on the turntable',exact:true}).click();
 await page.locator('.transfer-layer').waitFor({state:'detached'});
 assert(await page.locator('#detail-dialog').evaluate(el=>el.scrollWidth<=el.clientWidth),'Mobile turntable fits');
 await page.locator('.artist-archive').scrollIntoViewIfNeeded();
 await page.screenshot({path:'output/playwright/contact-sheet-mobile.png'});
 await page.locator('.artist-archive button').first().click();
 await page.locator('#photo-dialog img').evaluate(el=>Promise.all(el.getAnimations().map(a=>a.finished)));
 assert(await page.locator('#photo-dialog').isVisible(),'Contact print lifts to viewer');
 await page.keyboard.press('Escape');await page.keyboard.press('Escape');await page.locator('#detail-dialog').waitFor({state:'hidden'});
 await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'Put it on the turntable',exact:true}).click();
 assert(await page.locator('.transfer-layer').count()===0,'Reduced motion skips transfer');
 assert(errors.length===0,'Runtime errors: '+errors.join(';'));
 await page.keyboard.press('Escape');await page.emulateMedia({reducedMotion:'no-preference'});
 await page.getByRole('button',{name:'Put it on the turntable',exact:true}).click();await page.keyboard.press('Escape');await page.goto('http://127.0.0.1:5173/#record-12112689');await page.locator('#detail-title').waitFor();await page.locator('.transfer-layer').waitFor({state:'detached'});assert(await page.locator('#detail-dialog').isVisible(),'Interrupted close preserves new release');assert(await page.locator('#detail-title').textContent()==='Yeni Bir Gün','New release after interrupted transition');await page.keyboard.press('Escape');await page.locator('#detail-dialog').waitFor({state:'hidden'});
 console.log('PASS: drag/inertia, adaptive light, forward/reverse transfer, sides/tracks, tonearm, braking, room, contact sheet, reduced motion and mobile.');
}
