// English editorial summaries adapted from the supplied Ukrainian collection notes.
export const summaries = [
`KARNA reimagines familiar songs through acoustic textures and Carpathian melodies. Rather than a conventional unplugged collection, it opens a quieter chapter in the band's musical world. This numbered Carpathian Mist pressing is a 99-copy edition.`,
`An intimate blend of indie rock, spoken rhythm and distinctly Lviv imagery. Khrystyna Soloviy's appearance and the poetry of Maksym Kryvtsov in “На Дорогах” give the album a deeply personal, wartime context.`,
`Ulyana Del Rey brings Ukrainian humour, internet culture and alternative pop into the physical world of vinyl. The limited Milky Purple Splash pressing is part of this release's visual character.`,
`Eve explores relationships through the Alan Parsons Project's carefully layered studio sound. Voices, instrumental passages and polished arrangements build a continuous album experience. This copy is the 1979 German gatefold misprint.`,
`A reinvention of Yes, with direct songwriting, electronic textures and Trevor Rabin's guitar sound. “Owner of a Lonely Heart” is the best-known doorway into a record that takes progressive rock toward eighties pop.`,
`Japanese jazz and funk meet on Memory Lane, where rhythm and ensemble interplay are central to the listening experience. This collection holds the limited 2025 Clear Sky Blue reissue.`,
`The Police expand their trio sound with synthesizers and horns, keeping the tension between reggae rhythms and rock. “Spirits in the Material World” and “Every Little Thing She Does Is Magic” reveal the album's two sides.`,
`A compilation of Glenn Miller's big-band world: close ensemble writing, a distinctive reed sound and dance-band momentum. This Czechoslovak pressing brings swing-era recordings into a later listening context.`,
`The Czechoslovak edition of Close to the Edge places a landmark of progressive rock behind a translated title. Extended forms, shifting textures and the interaction of the five musicians reward listening to complete sides.`,
`The Last Dinner Party's second album develops their theatrical approach to rock. The Inferno red-and-pink pressing makes the physical edition part of the album's dramatic presentation.`,
`Pyramid builds a world of mystery through orchestration, spacious production and accessible songs. The 1978 German pressing preserves the album as a sequence of connected moods.`,
`An album centred on chance, temptation and the imagery of gambling. The closing suite gives the Alan Parsons Project's polished songwriting a longer dramatic arc.`,
`Måneskin bring forceful vocals, bass-driven momentum and direct rock arrangements to Teatro d'Ira. This 2021 light-orange transparent edition captures the band at a defining moment.`,
`Paul and Linda McCartney's Ram combines home-spun freedom with intricately built arrangements. Its changes of scale, harmonies and playful ideas are best heard as a whole album. This copy is the 2017 remaster.`,
`Scott Joplin's ragtime is presented through ensemble arrangements associated with the Red Back Book. Listen for the dialogue between syncopation, steady pulse and instrumental colour.`,
`This East German compilation gathers Eric Clapton's work into a different regional release history. Its value lies both in the music and in the way an international catalogue reached local listeners.`,
`Edgar Allan Poe's writing becomes the basis for the Alan Parsons Project's debut: voices, orchestra and studio experimentation create a dark narrative atmosphere. This is the 1976 German reissue.`,
`A second pressing of the Poe-inspired debut in the collection. The 1978 German gatefold repress offers a distinct physical edition of the same original material.`,
`I Robot turns questions about technology and humanity into cinematic progressive pop. Synthesizers, choir and meticulously arranged rhythm tracks create a world that feels both mechanical and deeply human.`,
`Barış Manço and Kurtalan Ekspres combine Anatolian musical identity with a progressive rock vocabulary. Yeni Bir Gün moves between song and expansive instrumental passages; this copy is the 2018 remaster.`,
`Yessongs captures Yes on a larger concert scale. The triple album lets long compositions unfold with the energy and looseness of live performance. This collection contains a 1977 German reissue.`,
`Glenn Miller's orchestra is heard through a collection of original recordings. The arrangements make individual sections speak as a single, instantly recognisable ensemble.`,
`Low juxtaposes concise, fragmented songs with atmospheric instrumental pieces. Bowie's changing musical language makes the two sides feel like different rooms within the same emotional landscape.`,
`The soundtrack to Staying Alive brings together songs written for the film and its dance-oriented world. This German gatefold edition situates the music in the pop production of 1983.`,
`Plastic Letters finds Blondie moving between punk energy, pop craft and an emerging new-wave identity. Short, characterful songs keep the album restless and immediate.`,
`Let's Dance gives David Bowie's songs a striking dance-floor presence. Rhythm, production detail and guitar colour work together without erasing the tension beneath the glossy surface. This is the Indian pressing.`,
`Thriller moves fluently between pop, funk, rock and R&B. The precision of its arrangements and contrasts between songs help explain why it works as an album beyond its familiar singles.`,
`Pink Floyd link songs through recurring sounds and themes of time, money and human pressure. The album's continuous structure makes turning a record side part of the listening ritual.`,
`True Blue presents Madonna's increasingly assured pop songwriting through bright, carefully constructed arrangements. This Czechoslovak edition is a 1987 pressing.`,
`Colosseum Live lets jazz, blues and rock expand on stage. Ensemble exchanges and extended performances give the double album its physical momentum.`,
`Abacab strips back parts of Genesis's earlier sound while experimenting with rhythm, repetition and studio textures. The Bulgarian Blue Label pressing adds a regional chapter to the album's release history.`,
`The Wall uses songs, voices and sound effects to build a story of isolation. The double-album format gives its recurring musical ideas room to change meaning as the narrative develops.`,
`Spliff's 85555 joins German-language songwriting with rock, electronics and new-wave production. The band's rhythmic precision gives even its stranger moments a strong pop framework.`,
`A seven-inch single pairing “Halabala Rock'n Roll” with “Moucha”. This small-format record documents the local adaptation and circulation of rock-and-roll material in Czechoslovakia.`,
`Two songs from Karel Gott on a Czechoslovak seven-inch pressing. The single format places the focus on vocal interpretation and the contrast between its A and B sides.`,
`Katapult's “Katapult” and “Blues” capture the compact, direct character of a rock single. This collection holds the 1979 Czechoslovak repress.`,
`Waldemar Matuška's voice connects popular song with a storytelling tradition. This 1970 mono single pairs “Co Je Žito” with “In Vino Veritas”.`,
`Pure Gold is a compact route into Elvis Presley's catalogue. The compilation also shows how earlier American recordings were repackaged for Czechoslovak listeners.`,
`Chuck Berry's guitar language, storytelling and propulsive rhythms form a foundation of rock and roll. This Yugoslav compilation brings that work together in a local edition.`,
`Billie Holiday's phrasing changes the emotional weight of a line through timing and tone. This mono collection invites close listening to her relationship with the accompanying musicians.`,
`Johnny Cash's Prague concert brings his songs into a distinctive live setting. The record preserves the exchange between a recognisable performer and a local audience.`,
`Radio Afrodita connects Martvyj Piven's music with the literary character of Ukrainian rock. This numbered 2025 pressing makes a later physical chapter in the life of the original material.`,
`Corey Hart's Young Man Running belongs to the expansive production world of late-eighties pop rock. Vocal presence and carefully shaped arrangements guide the album.`,
`A Soviet-era Deep Purple compilation, catalogued as an unofficial release. Alongside the music, this copy records a particular history of access, repackaging and circulation.`,
`Delicate Sound of Thunder presents Pink Floyd's late-eighties live sound across two records. This Soviet pressing has its own label and sleeve characteristics, distinct from the original concert release.`,
`Louis Armstrong's Prague performance preserves a meeting between an international jazz figure and a local concert audience. Listen for the interplay of trumpet, voice and the live ensemble.`,
`Dead Club City frames Nothing But Thieves' alternative rock through a fictional urban setting. Synthesizers and dance-oriented rhythms bring a new texture to the band's sound.`,
`Led Zeppelin's untitled fourth album balances hard rock, acoustic passages and folk-inflected atmosphere. This 2014 remaster presents the familiar sequence in a heavyweight gatefold edition.`,
`AM centres on weighty, repeating riffs, close rhythms and contrasting vocal layers. Arctic Monkeys give the album a consistent late-night atmosphere without making every song behave the same way.`,
`Come Fly With Me turns travel imagery into a sequence of orchestral songs. Sinatra's phrasing moves within the arrangements with conversational ease. This collection holds a blue-vinyl reissue.`,
`Bill Haley and the Comets bring swing-derived momentum into early rock and roll. This compilation preserves the dance-band energy behind the familiar songs.`,
`Wish You Were Here Tonight places Ray Charles's expressive voice within early-eighties production. His phrasing remains the centre of the record's changing musical settings.`,
`Nevermind combines abrasive guitar energy with sharply defined melodic writing. Contrasts between restrained verses and explosive releases are central to its physical impact.`,
`Patient Number 9 surrounds Ozzy Osbourne's distinctive voice with an expansive cast of rock musicians. The blue-and-yellow split double-vinyl edition adds a strong visual identity.`,
`In the Wee Small Hours builds a remarkably consistent nocturnal mood. Sinatra's measured phrasing and the restrained arrangements give quiet details unusual emotional force.`,
`Eva Olmerová's expressive singing meets an orchestra directed by Michael Kocáb. Listen for the balance between the personality of the voice and the colours of the ensemble.`,
`Bach's music is reimagined through Leopold Stokowski's orchestral transcriptions. The Czech Philharmonic gives the counterpoint a different scale, colour and sense of space.`,
`Karel Kryl's Plzeň '90 preserves songs in the charged setting of a 1990 performance. The 2023 gatefold release carries that concert into a new physical edition.`
];
