import {reduced,lightAlbum,wireCrate,departingSleeve,transferRecord,wireTurntable,photoLift,toggleRoom} from './experience.js';
import './style.css';
import {filterRecords, nextIndex, escapeHtml as e, safeUrl, markdown} from './catalogue.js';
import {summaries} from './english.js';
const words = {
 en:{room:'Record room',exitRoom:'Exit record room',flip:'Flip record',side:'Side',allTracks:'All tracks',hold:'Hold to slow the record',arm:'Tonearm position',archive:'Artist archive',archiveDate:'Photo date',archiveUnknown:'Date not documented',photographs:'Photography',photoHint:'The sleeve, the artists, the era',photo:'Photograph',previousPhoto:'Previous photograph',nextPhoto:'Next photograph',enlarge:'View full size',photoCredit:'Release photographs · Discogs contributors',ukNotes:'Original Ukrainian collection notes',brand:'Warm grooves',tag:'A PERSONAL VINYL COLLECTION',collection:'The collection',about:'A little about it',title:'Some things',italic:'sound better',last:'on vinyl.',intro:'A sleeve to hold. A needle to drop.\nA little time to get lost in the music.',browse:'TAKE YOUR TIME. FIND YOUR RECORD.',records:'records',years:'years of music',countries:'countries',featured:'ON THE SLEEVE',explore:'Put it on the turntable',hint:'Scroll or swipe to dig through',search:'Search & filter',placeholder:'Artist, album, label…',allGenres:'All genres',allFormats:'All formats',lp:'Albums / LPs',single:'7-inch singles',order:'Collection order',artist:'Artist A–Z',year:'Original year · newest',reset:'Clear filters',empty:'No records in this crate.',emptyText:'Try a different artist or give your filters a fresh start.',shelf:'A few from the shelf',shelfSub:'Different decades. Same ritual.',all:'See all records',back:'Back to the collection',original:'ORIGINAL MATERIAL',pressing:'YOUR PRESSING',country:'COUNTRY / MARKET',label:'LABEL & CATALOGUE',format:'FORMAT',condition:'MEDIA / SLEEVE',rating:'MY RATING',story:'Behind the record',tracks:'The tracklist',sources:'Sources & artwork',discogs:'View this pressing on Discogs',gallery:'Explore the sleeve & labels',notes:'Collection notes',pause:'Pause rotation',spin:'Spin the record',visual:'A visual listening ritual · no audio playback',close:'Close',prev:'Previous record',next:'Next record',random:'Surprise me',footer:'Collected with care. Played with love.',made:'ANALOG SOUL. DIGITAL HOME.',install:'Install collection',offline:'Offline · the collection stays with you',ready:'Available offline',aboutTitle:'A small collection.\nA whole world of sound.',aboutText:'This is Ihor’s personal record shelf: Ukrainian releases, progressive rock, jazz, old favourites and unexpected finds. Every pressing has its own place, and every sleeve has a story.',aboutMore:'58 releases, documented in a personal Discogs catalogue. Pressing dates are kept separate from the original recording dates. Artwork and release details belong to their respective artists, labels and contributors. English listening notes are adapted from the Ukrainian catalogue.',aboutEnd:'Pick a record. Give it a little time.',results:'matching records',grid:'All records',view:'Open record',unrated:'Not rated',unknown:'Not documented',motion:'Motion',on:'On',off:'Off'},
 uk:{room:'Кімната платівок',exitRoom:'Вийти з кімнати',flip:'Перевернути платівку',side:'Сторона',allTracks:'Усі треки',hold:'Утримуйте, щоб сповільнити платівку',arm:'Положення тонарма',archive:'Архів виконавця',archiveDate:'Дата фото',archiveUnknown:'Дату не зазначено',photographs:'Фотографії',photoHint:'Конверт, виконавці та епоха',photo:'Фотографія',previousPhoto:'Попереднє фото',nextPhoto:'Наступне фото',enlarge:'На весь екран',photoCredit:'Фотографії видання · спільнота Discogs',ukNotes:'Оригінальні нотатки українською',brand:'Теплий звук',tag:'ОСОБИСТА ВІНІЛОВА КОЛЕКЦІЯ',collection:'Колекція',about:'Трохи про неї',title:'Деякі речі',italic:'краще звучать',last:'на вінілі.',intro:'Взяти конверт. Опустити голку.\nНа мить загубитися в музиці.',browse:'НЕ ПОСПІШАЙТЕ. ЗНАЙДІТЬ СВОЮ ПЛАТІВКУ.',records:'платівок',years:'років музики',countries:'країн',featured:'НА КОНВЕРТІ',explore:'Покласти на програвач',hint:'Гортайте коліщатком або свайпом',search:'Пошук і фільтри',placeholder:'Виконавець, альбом, лейбл…',allGenres:'Усі жанри',allFormats:'Усі формати',lp:'Альбоми / LP',single:'7-дюймові сингли',order:'Порядок колекції',artist:'За виконавцем',year:'Рік оригіналу · новіші',reset:'Скинути фільтри',empty:'У цьому ящику поки порожньо.',emptyText:'Спробуйте іншого виконавця або скиньте фільтри.',shelf:'Дещо з полиці',shelfSub:'Різні десятиліття. Той самий ритуал.',all:'Усі платівки',back:'Назад до колекції',original:'ОРИГІНАЛЬНИЙ МАТЕРІАЛ',pressing:'ВАШЕ ВИДАННЯ',country:'КРАЇНА / РИНОК',label:'ЛЕЙБЛ І КАТАЛОЖНИЙ НОМЕР',format:'ФОРМАТ',condition:'ПЛАТІВКА / КОНВЕРТ',rating:'МОЯ ОЦІНКА',story:'Історія платівки',tracks:'Треклист',sources:'Джерела й оформлення',discogs:'Це видання на Discogs',gallery:'Конверт, розворот та етикетки',notes:'Нотатки колекції',pause:'Зупинити обертання',spin:'Обертати платівку',visual:'Візуальний ритуал · без відтворення аудіо',close:'Закрити',prev:'Попередня платівка',next:'Наступна платівка',random:'Здивуйте мене',footer:'Зібрано дбайливо. Зіграно з любов’ю.',made:'АНАЛОГОВА ДУША. ЦИФРОВИЙ ДІМ.',install:'Встановити колекцію',offline:'Офлайн · колекція залишається з вами',ready:'Доступно офлайн',aboutTitle:'Маленька колекція.\nЦілий світ звуку.',aboutText:'Це особиста полиця Ігоря: українські релізи, прогресивний рок, джаз, давні улюбленці й несподівані знахідки. Кожне видання має своє місце, а кожен конверт — свою історію.',aboutMore:'58 релізів із особистого каталогу Discogs. Дати конкретного видання відокремлено від дат оригінального матеріалу. Обкладинки й дані належать відповідним виконавцям, лейблам та авторам. Англійські нотатки адаптовано з українського каталогу.',aboutEnd:'Оберіть платівку. Приділіть їй трохи часу.',results:'платівок знайдено',grid:'Усі платівки',view:'Відкрити платівку',unrated:'Без оцінки',unknown:'Не зазначено',motion:'Анімація',on:'Увімк.',off:'Вимк.'}
};
const icons={search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4 4"/>',arrow:'<path d="M4 12h15m-6-6 6 6-6 6"/>',left:'<path d="m14 6-6 6 6 6"/>',right:'<path d="m10 6 6 6-6 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',grid:'<rect x="4" y="4" width="6" height="6"/><rect x="14" y="4" width="6" height="6"/><rect x="4" y="14" width="6" height="6"/><rect x="14" y="14" width="6" height="6"/>',shuffle:'<path d="M3 6h3c5 0 7 12 12 12h3m-4-4 4 4-4 4M3 18h3c2 0 4-3 5-5m2-3c2-3 3-4 5-4h3m-4-4 4 4-4 4"/>',disc:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="3"/><path d="M5 12a7 7 0 0 1 7-7"/>'};
const icon=(key)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[key]||icons.disc}</svg>`;
const read=(key,fallback)=>{try{return localStorage.getItem(key)||fallback;}catch{return fallback;}};
const save=(key,value)=>{try{localStorage.setItem(key,value);}catch{/* Storage is optional. */}};
let lang=read('vinyl-language','uk'); if(!words[lang])lang='uk';
let motion=read('vinyl-motion',matchMedia('(prefers-reduced-motion: reduce)').matches?'off':'on');
let dialogSequence=0,returnRect=null,closing=false,transitionPromise=Promise.resolve();
let galleries={}, archives={}, galleryIndex=0;
let records=[], filtered=[], index=0, view='stack', filters={query:'',genre:'all',format:'all',sort:'collection'}, searchOpen=false, selected=null, installEvent=null, priorFocus=null;
const t=key=>words[lang][key]||key;
const asset=path=>{if(!path)return path; if(/^https?:/.test(path))return path; return `${import.meta.env.BASE_URL}${String(path).replace(/^\/+/, '')}`;};
const app=document.querySelector('#app');
const countriesUk={'Ukraine':'Україна','Germany':'Німеччина','Czechoslovakia':'Чехословаччина','Japan':'Японія','Europe':'Європа','German Democratic Republic (GDR)':'НДР','UK':'Велика Британія','Turkey':'Туреччина','US':'США','India':'Індія','Bulgaria':'Болгарія','Yugoslavia':'Югославія','USSR':'СРСР','Czech Republic':'Чехія'};
const original=r=>lang==='uk'?r.original:r.original.replaceAll('1930-ті','1930s').replaceAll('1950-ті','1950s').replaceAll('1960-ті','1960s').replaceAll('1980-ті','1980s').replace('11 квітня 1978','11 April 1978').replace('18 березня 1965','18 March 1965').replace('10–11 січня 1990','10–11 January 1990').replace('1969–1972 записи; 1990 компіляція','1969–1972 recordings; 1990 compilation').replace('барокові твори XVIII ст.; оркестровка Stokowski — XX ст.','18th-century compositions; 20th-century Stokowski orchestrations');
const country=r=>lang==='uk'?(countriesUk[r.country]||r.country):r.country;
const summary=r=>lang==='uk'?r.summaryUk:summaries[r.number-1];
const cover=(r,cls='',lazy=true)=>`<img class="${cls}" src="${asset(r.cover)}" alt="${e(r.artist)} — ${e(r.title)}" ${lazy?'loading="lazy"':'fetchpriority="high"'} draggable="false" width="600" height="600">`;
function disk(r,cls=''){return `<div class="vinyl ${cls}" aria-hidden="true"><div class="vinyl-label" style="background-image:url('${asset(r.cover)}')"><span></span></div></div>`;}
function render(){
 document.documentElement.lang=lang; document.documentElement.dataset.motion=motion;
 document.title=`${t('brand')} · ${lang==='uk'?'Вінілова колекція':'Vinyl collection'}`;
 app.innerHTML=`<button class="room-exit" data-action="room-exit" hidden>${t('exitRoom')} ×</button><header class="header"><a class="brand" href="#" aria-label="${t('collection')}"><span class="brand-disc">${icon('disc')}</span><span class="header-count">58</span></a><div class="header-tools"><button class="lang ${lang==='uk'?'active':''}" data-lang="uk" aria-pressed="${lang==='uk'}">УКР</button><span>/</span><button class="lang ${lang==='en'?'active':''}" data-lang="en" aria-pressed="${lang==='en'}">ENG</button><button class="icon-button search-toggle" data-action="search" aria-label="${t('search')}" aria-expanded="${searchOpen}">${icon('search')}</button></div></header>
 <main id="collection"><section class="hero">
 <div class="collection-player"><div class="player-top"><span class="player-speed" aria-hidden="true">33⅓</span><div class="view-tools"><button class="icon-button" data-action="room" aria-label="${t('room')}" aria-pressed="false">⛶</button><button class="icon-button" data-action="random" aria-label="${t('random')}">${icon('shuffle')}</button><button class="icon-button" data-action="grid" aria-label="${t('grid')}">${icon('grid')}</button></div></div><div id="filter-panel" ${searchOpen?'':'hidden'}>${filterMarkup()}</div><div id="record-area"></div></div></section>
 <section class="shelf-section"><div class="section-heading"><div><h2>${t('shelf')}</h2></div><button class="text-button" data-action="grid">${t('all')} ${icon('arrow')}</button></div><div class="shelf">${[19,2,23,6,28,42].map(n=>{const r=records[n-1];return `<button class="shelf-item" data-record="${r.id}"><div class="shelf-cover">${cover(r)}<span>${icon('arrow')}</span></div><span class="shelf-artist">${e(r.artist)}</span><span class="shelf-title">${e(r.title)}</span></button>`;}).join('')}</div></section></main>
 <footer><button class="footer-about" data-action="about">${t('about')}</button><button class="motion-toggle" data-action="motion">${t('motion')}: ${motion==='on'?t('on'):t('off')}</button><button id="install" data-action="install" ${installEvent?'':'hidden'}>${t('install')} ↗</button><span id="connection" class="connection" role="status">${navigator.onLine?'':t('offline')}</span></footer><dialog id="detail-dialog" aria-labelledby="detail-title"></dialog><dialog id="about-dialog" aria-labelledby="about-title"></dialog><dialog id="photo-dialog" aria-label="${t('photographs')}"></dialog>`;
 bind(); renderRecord();
}
function filterMarkup(){const genres=[...new Set(records.flatMap(r=>r.genres))].sort();return `<div class="search-field">${icon('search')}<input id="search" type="search" aria-label="${t('search')}" placeholder="${t('placeholder')}" value="${e(filters.query)}"><button class="icon-button" data-action="search" aria-label="${t('close')}">${icon('close')}</button></div><div class="filter-selects"><select id="genre" aria-label="${t('allGenres')}"><option value="all">${t('allGenres')}</option>${genres.map(g=>`<option ${filters.genre===g?'selected':''} value="${e(g)}">${e(g)}</option>`).join('')}</select><select id="format" aria-label="${t('allFormats')}">${[['all','allFormats'],['lp','lp'],['single','single']].map(([v,k])=>`<option value="${v}" ${filters.format===v?'selected':''}>${t(k)}</option>`).join('')}</select><select id="sort" aria-label="${t('order')}">${[['collection','order'],['artist','artist'],['year','year']].map(([v,k])=>`<option value="${v}" ${filters.sort===v?'selected':''}>${t(k)}</option>`).join('')}</select><button class="reset-button" data-action="reset">${t('reset')}</button></div>`;}
function renderRecord(direction=0){
 const area=document.querySelector('#record-area');
 filtered=filterRecords(records,filters);index=Math.min(index,Math.max(0,filtered.length-1));
 if(!filtered.length){area.innerHTML=`<div class="empty">${icon('disc')}<h2>${t('empty')}</h2><p>${t('emptyText')}</p><button class="primary" data-action="reset">${t('reset')}</button></div>`;return;}
 if(view==='grid'){area.innerHTML=`<div class="grid-heading"><span>${filtered.length} ${t('results')}</span><button class="text-button" data-action="stack">${t('back')} ${icon('arrow')}</button></div><div class="record-grid">${filtered.map(r=>`<button class="grid-record" data-record="${r.id}">${cover(r)}<strong>${e(r.artist)}</strong><span>${e(r.title)}</span></button>`).join('')}</div>`;return;}
 const r=filtered[index];lightAlbum(r.cover);document.querySelector('.player-speed').textContent=r.format.includes('45 RPM')?'45':'33⅓';const previous=filtered[nextIndex(index,-1,filtered.length)], next=filtered[nextIndex(index,1,filtered.length)];
 area.innerHTML=`<div class="record-stage ${direction>0?'slide-next':direction<0?'slide-prev':''}" aria-label="${t('collection')}"><div class="stage-shadow"></div><button class="back-sleeve back-one" data-action="next" aria-label="${t('next')}" ${filtered.length<2?'hidden':''}>${cover(next,'',false)}</button><button class="back-sleeve back-two" data-action="prev" aria-label="${t('prev')}" ${filtered.length<2?'hidden':''}>${cover(previous,'',false)}</button><div class="main-record">${disk(r)}<button class="front-sleeve" data-record="${r.id}" aria-label="${t('view')}: ${e(r.title)}">${cover(r,'',false)}<span class="sleeve-edge"></span><span class="sleeve-open">${icon('arrow')}</span></button></div></div>
 <div class="record-caption" aria-live="polite"><div class="record-number">${String(index+1).padStart(2,'0')}<span> / ${String(filtered.length).padStart(2,'0')}</span></div><div class="record-title"><p>${e(r.artist)}</p><h2>${e(r.title)}</h2><div class="record-tags"><span>${e(r.original.match(/\d{4}/)?.[0]||r.original)}</span><i></i><span>${e(r.genres.slice(0,2).join(' / '))}</span><i></i><span>${r.format.includes('7"')?'7″':'LP'}</span></div></div><div class="arrows"><button class="round-button" data-action="prev" aria-label="${t('prev')}" ${filtered.length<2?'disabled':''}>${icon('left')}</button><button class="round-button" data-action="next" aria-label="${t('next')}" ${filtered.length<2?'disabled':''}>${icon('right')}</button></div></div><div class="player-bottom"><span class="scroll-hint" aria-label="${t('hint')}">↕</span><button class="text-button put-on" data-record="${r.id}">${t('explore')} ${icon('arrow')}</button></div>`;
 bindStage();
}
function advance(delta){departingSleeve(document.querySelector('.record-stage'),delta);const action=document.activeElement?.dataset.action;index=nextIndex(index,delta,filtered.length);renderRecord(delta);if(action==='next'||action==='prev')document.querySelector(`.arrows [data-action="${action}"]`)?.focus({preventScroll:true});}
let wheelLock=0;
function bindStage(){const stage=document.querySelector('.record-stage');if(!stage)return;
 stage.addEventListener('wheel',event=>{if(Math.abs(event.deltaY)<8)return;event.preventDefault();const now=Date.now();if(now-wheelLock<650)return;wheelLock=now;advance(event.deltaY>0?1:-1);},{passive:false});
 wireCrate(stage,advance);
}
function bind(){
 app.onclick=event=>{const langButton=event.target.closest('[data-lang]');if(langButton){lang=langButton.dataset.lang;save('vinyl-language',lang);render();return;}
 const item=event.target.closest('[data-record]');if(item){openRecord(Number(item.dataset.record),true,item.querySelector('img')||document.querySelector('.front-sleeve img'));return;}
 const action=event.target.closest('[data-action]')?.dataset.action;
 if(action==='room')toggleRoom();if(action==='room-exit')toggleRoom(false);
 if(action==='next')advance(1);if(action==='prev')advance(-1);
 if(action==='random'){if(filtered.length>1)advance(1+Math.floor(Math.random()*(filtered.length-1)));}
 if(action==='grid'||action==='stack'){view=action==='grid'?'grid':'stack';renderRecord();document.querySelector('.collection-player').scrollIntoView({behavior:motion==='on'?'smooth':'instant',block:'start'});}
 if(action==='search'){searchOpen=!searchOpen;const panel=document.querySelector('#filter-panel');panel.hidden=!searchOpen;document.querySelector('.search-toggle').setAttribute('aria-expanded',String(searchOpen));if(searchOpen)document.querySelector('#search').focus();}
 if(action==='reset'){filters={query:'',genre:'all',format:'all',sort:'collection'};index=0;document.querySelector('#filter-panel').innerHTML=filterMarkup();bindFilters();renderRecord();}
 if(action==='about')openAbout();if(action==='close')closeDialogs();
 if(action==='motion'){motion=motion==='on'?'off':'on';save('vinyl-motion',motion);document.documentElement.dataset.motion=motion;event.target.closest('button').textContent=`${t('motion')}: ${motion==='on'?t('on'):t('off')}`;}
 if(action==='rotation'){const turntable=document.querySelector('.turntable');const paused=turntable.classList.toggle('paused');event.target.closest('button').textContent=paused?t('spin'):t('pause');event.target.closest('button').setAttribute('aria-pressed',String(!paused));}
 if(action==='install')install();
 if(action==='photo-next')changePhoto(1);if(action==='photo-prev')changePhoto(-1);if(action==='photo-full')openPhoto();if(action==='photo-close')document.querySelector('#photo-dialog').close();
 const archiveButton=event.target.closest('[data-archive]');if(archiveButton){galleryIndex=Number(archiveButton.dataset.archive);openPhoto();}
 const thumb=event.target.closest('[data-photo]');if(thumb){galleryIndex=Number(thumb.dataset.photo);renderGallery();}
 };
 bindFilters();for(const dialog of document.querySelectorAll('dialog')){dialog.addEventListener('cancel',event=>{if(dialog.id==='detail-dialog'&&!reduced()){event.preventDefault();closeDialogs();}});dialog.addEventListener('click',event=>{if(event.target===dialog){if(dialog.id==='photo-dialog')dialog.close();else closeDialogs();}});dialog.addEventListener('close',()=>{if(dialog.open)return;if(dialog.id==='photo-dialog'){if(document.querySelector('#detail-dialog').open)document.body.classList.add('modal-open');document.querySelector('[data-action="photo-full"]')?.focus();return;}document.body.classList.remove('modal-open');if(dialog.id==='detail-dialog'&&!dialog.open&&location.hash===dialog.dataset.hash)history.replaceState(null,'',location.pathname+location.search);selected=null;lightAlbum(filtered[index]?.cover);priorFocus?.focus();});}
}
function bindFilters(){document.querySelector('#search').oninput=event=>{filters.query=event.target.value;index=0;renderRecord();};for(const name of ['genre','format','sort'])document.querySelector(`#${name}`).onchange=event=>{filters[name]=event.target.value;index=0;renderRecord();};}
function openRecord(id,updateUrl=true,origin=null){const r=records.find(r=>r.id===id);if(!r)return;dialogSequence++;selected=r;lightAlbum(r.cover);closing=false;returnRect=(origin||document.querySelector('.front-sleeve img'))?.getBoundingClientRect();galleryIndex=0;priorFocus=document.activeElement;
 const dialog=document.querySelector('#detail-dialog');const fact=(label,value)=>`<div><dt>${t(label)}</dt><dd>${e(value||t('unknown'))}</dd></div>`;
 dialog.innerHTML=`<div class="detail-top"><button class="text-button" data-action="close">${icon('left')}${t('back')}</button><span class="eyebrow">№ ${String(r.number).padStart(2,'0')} / 58</span><button class="icon-button" data-action="close" aria-label="${t('close')}">${icon('close')}</button></div><div class="detail-layout"><div class="detail-visual"><div class="turntable ${motion==='off'?'paused':''}"><div class="platter"></div>${disk(r,'playing-disc')}<div class="tonearm"><span></span></div><span class="turntable-brand">WARM GROOVES <small>DIRECT DRIVE / STEREO</small></span><span class="power-light"></span><span class="speed">${r.format.includes('45 RPM')?'45':'33⅓'}</span></div><div class="unpacking-sleeve">${cover(r,'',false)}</div><div class="turntable-controls"><button class="text-button" data-action="rotation" aria-pressed="${motion==='on'}">${motion==='on'?t('pause'):t('spin')}</button><span>${t('visual')}</span></div><dl class="pressing-facts">${fact('pressing',r.date)}${fact('country',country(r))}${fact('format',r.format)}${fact('label',r.label)}${fact('condition',r.condition==='—'?t('unknown'):r.condition)}${fact('rating',r.rating.startsWith('—')?t('unrated'):r.rating)}</dl><section class="release-gallery" aria-label="${t('photographs')}"><h3>${t('photographs')}</h3><p>${t('photoHint')}</p><div id="gallery-content"></div></section></div><article class="record-story"><p class="eyebrow">${e(r.artist)}</p><h2 id="detail-title">${e(r.title)}</h2><div class="detail-tags"><span>${e(original(r))}</span><span>${e(r.genres.join(' / '))}</span></div><h3>${t('story')}</h3><div class="summary">${markdown(summary(r))}</div>${lang==='uk'?Object.entries(r.sectionsUk).map(([title,body])=>`<details class="story-note"><summary>${e(title)}</summary>${markdown(body)}</details>`).join(''):''}<h3 class="track-heading">${t('tracks')}<span>${r.tracks.length}</span></h3><ol class="tracklist">${r.tracks.map(track=>`<li><span class="track-position">${e(track.position)}</span><span>${e(track.title)}</span><span class="duration">${e(track.duration)}</span></li>`).join('')}</ol><div class="source-links"><h3>${t('sources')}</h3><a href="${e(safeUrl(r.url))}" target="_blank" rel="noopener noreferrer">${t('discogs')} ↗</a><a href="${e(safeUrl(r.gallery))}" target="_blank" rel="noopener noreferrer">${t('gallery')} ↗</a>${r.sources.map(url=>`<a href="${e(safeUrl(url))}" target="_blank" rel="noopener noreferrer">${e(new URL(url).hostname.replace('www.',''))} ↗</a>`).join('')}</div></article></div>`;
 dialog.dataset.hash=`#record-${r.id}`;document.body.classList.add('modal-open');dialog.showModal();dialog.scrollTop=0;renderGallery();wireTurntable(dialog,{flip:t('flip'),side:t('side'),all:t('allTracks'),hold:t('hold'),arm:t('arm'),spin:t('spin'),pause:t('pause')});transitionPromise=transferRecord(dialog,returnRect,dialog.querySelector('.unpacking-sleeve'),dialog.querySelector('.playing-disc'));if(updateUrl)history.pushState(null,'',`#record-${r.id}`);
}
function pressingPhotos(){return galleries[String(selected?.id)]?.length?galleries[String(selected.id)]:[{src:selected.cover,number:1}];}
function photos(){return [...pressingPhotos(),...(archives[String(selected?.id)]||[])];}
function photoCredit(photo){return photo.kind==='archive'?`<strong>${e(photo.caption)}</strong><br>${t('archiveDate')}: ${e(photo.date||t('archiveUnknown'))}<br>${e(photo.author)} · <a href="${e(safeUrl(photo.licenseUrl||photo.source))}" target="_blank" rel="noopener noreferrer">${e(photo.license)}</a> · <a href="${e(safeUrl(photo.source))}" target="_blank" rel="noopener noreferrer">Wikimedia Commons ↗</a>`:t('photoCredit');}
function galleryImage(photo){return `<img src="${asset(photo.src)}" alt="${e(selected.artist)} — ${e(selected.title)} · ${t('photo')} ${galleryIndex+1}" width="${photo.width||600}" height="${photo.height||600}">`;}
function galleryControls(){return `<button class="round-button" data-action="photo-prev" aria-label="${t('previousPhoto')}" ${photos().length<2?'disabled':''}>${icon('left')}</button><span aria-live="polite">${String(galleryIndex+1).padStart(2,'0')} <i>/ ${String(photos().length).padStart(2,'0')}</i></span><button class="round-button" data-action="photo-next" aria-label="${t('nextPhoto')}" ${photos().length<2?'disabled':''}>${icon('right')}</button>`;}
function renderGallery(){if(!selected)return;const list=photos(),photo=list[galleryIndex];document.querySelector('#gallery-content').innerHTML=`<button class="gallery-image" data-action="photo-full" aria-label="${t('enlarge')}">${galleryImage(photo)}<span>${t('enlarge')} ↗</span></button><div class="gallery-navigation">${galleryControls()}</div><div class="gallery-thumbnails" aria-label="${t('photographs')}">${list.map((p,i)=>`<button data-photo="${i}" class="${i===galleryIndex?'selected':''}" aria-label="${t('photo')} ${i+1}" aria-pressed="${i===galleryIndex}"><img src="${p.src}" alt="" loading="lazy" width="80" height="80"></button>`).join('')}</div><p class="photo-credit">${photoCredit(photos()[galleryIndex])}</p>`;
 const archive=archives[String(selected.id)]||[];const content=document.querySelector('#gallery-content');if(archive.length)content.insertAdjacentHTML('beforeend',`<section class="artist-archive" aria-label="${t('archive')}"><h3>${t('archive')}</h3><div class="archive-strip">${archive.map((p,i)=>`<button data-archive="${i+pressingPhotos().length}"><img src="${p.src}" alt="${e(p.caption)}" loading="lazy" width="${p.width}" height="${p.height}"><span>${e(p.caption)}</span><small>${e(p.date||t('archiveUnknown'))}</small></button>`).join('')}</div></section>`);
 const full=document.querySelector('#photo-dialog');if(full.open){renderFullPhoto();photoLift(full);}
 const target=document.querySelector('.gallery-image');let startX=0;target.ontouchstart=event=>{startX=event.touches[0].clientX;};target.ontouchend=event=>{const delta=event.changedTouches[0].clientX-startX;if(Math.abs(delta)>40){event.preventDefault();changePhoto(delta<0?1:-1);}};
}
function changePhoto(delta){if(!selected)return;const focused=document.activeElement?.dataset.action;galleryIndex=nextIndex(galleryIndex,delta,photos().length);renderGallery();const scope=document.querySelector('#photo-dialog').open?'#photo-dialog':'#gallery-content';if(focused==='photo-next'||focused==='photo-prev')document.querySelector(`${scope} [data-action="${focused}"]`)?.focus({preventScroll:true});}
function renderFullPhoto(){document.querySelector('#photo-dialog').innerHTML=`<div class="photo-top"><span>${e(selected.artist)} — ${e(selected.title)}</span><button class="icon-button" data-action="photo-close" aria-label="${t('close')}">${icon('close')}</button></div><div class="full-photo">${galleryImage(photos()[galleryIndex])}</div><div class="gallery-navigation">${galleryControls()}</div><p class="photo-credit">${photoCredit(photos()[galleryIndex])}</p>`;}
function openPhoto(){const origin=document.activeElement?.querySelector('img')?.getBoundingClientRect()||document.querySelector('.gallery-image img')?.getBoundingClientRect();renderFullPhoto();const dialog=document.querySelector('#photo-dialog');dialog.showModal();photoLift(dialog,origin);}
function closeDialogs(animate=true){const detail=document.querySelector('#detail-dialog');if(animate&&!reduced()&&detail?.open){if(closing)return;closing=true;const sequence=dialogSequence;transitionPromise.then(()=>{if(sequence!==dialogSequence||!detail.open)return;detail.scrollTop=0;return transferRecord(detail,returnRect,detail.querySelector('.unpacking-sleeve'),detail.querySelector('.playing-disc'),true);}).finally(()=>{if(sequence!==dialogSequence)return;document.querySelectorAll('dialog[open]').forEach(d=>d.close());closing=false;});}else{dialogSequence++;document.querySelectorAll('dialog[open]').forEach(d=>d.close());closing=false;}}
function openAbout(){priorFocus=document.activeElement;const d=document.querySelector('#about-dialog');d.innerHTML=`<button class="icon-button about-close" data-action="close" aria-label="${t('close')}">${icon('close')}</button><span class="about-disc">${icon('disc')}</span><p class="eyebrow">${t('tag')}</p><h2 id="about-title">${t('aboutTitle').replace('\n','<br>')}</h2><p>${t('aboutText')}</p><p>${t('aboutMore')}</p><em>${t('aboutEnd')}</em>`;document.body.classList.add('modal-open');d.showModal();}
window.addEventListener('keydown',event=>{if(event.key==='Escape'&&document.body.classList.contains('record-room')&&!document.querySelector('dialog[open]')){toggleRoom(false);return;}if(document.querySelector('#photo-dialog[open]')){if(event.key==='ArrowRight'){event.preventDefault();changePhoto(1);}if(event.key==='ArrowLeft'){event.preventDefault();changePhoto(-1);}return;}if(document.querySelector('dialog[open]')||/INPUT|SELECT|TEXTAREA/.test(document.activeElement.tagName))return;if(event.key==='ArrowRight'||event.key==='ArrowDown'){event.preventDefault();advance(1);}if(event.key==='ArrowLeft'||event.key==='ArrowUp'){event.preventDefault();advance(-1);}if(event.key==='/'&&!event.metaKey&&!event.ctrlKey){event.preventDefault();if(!searchOpen)document.querySelector('[data-action="search"]').click();document.querySelector('#search').focus();}});
window.addEventListener('popstate',()=>{const id=Number(location.hash.replace('#record-',''));if(id&&records.some(r=>r.id===id)){closeDialogs(false);openRecord(id,false);}else closeDialogs(false);});
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installEvent=event;const button=document.querySelector('#install');if(button)button.hidden=false;});
async function install(){if(!installEvent)return;await installEvent.prompt();await installEvent.userChoice;installEvent=null;document.querySelector('#install').hidden=true;}
for(const event of ['online','offline'])window.addEventListener(event,()=>{document.querySelector('#connection').textContent=navigator.onLine?'':t('offline');});
async function init(){try{const response=await fetch(asset('/collection.json'));if(!response.ok)throw Error('Catalogue unavailable');records=await response.json();try{const galleryResponse=await fetch(asset('/gallery.json'));if(galleryResponse.ok)galleries=await galleryResponse.json();}catch{/* A record's local cover remains available. */}try{const archiveResponse=await fetch(asset('/archive.json'));if(archiveResponse.ok)archives=await archiveResponse.json();}catch{/* Archives are optional when metadata is unavailable. */}filtered=records;index=18;render();const deep=Number(location.hash.replace('#record-',''));if(deep)openRecord(deep,false);
 if(import.meta.env.PROD&&'serviceWorker' in navigator){navigator.serviceWorker.register(asset('/sw.js')).catch(error=>console.warn('Offline registration unavailable:',error));}
 }catch(error){app.innerHTML=`<div class="load-error"><h1>${t('brand')}</h1><p>${lang==='uk'?'Не вдалося завантажити колекцію. Оновіть сторінку.':'The collection could not load. Please reload the page.'}</p><button onclick="location.reload()">${lang==='uk'?'Спробувати ще':'Try again'}</button></div>`;console.error(error);}}
init();
